name: fml

version: 3.3.1+24

description:
  Framework Markup Language (FML) is a cross platform markup language. This package retrieves, parses, interprets and renders fml pages to native Flutter without the need to compile.

platforms:
  web:
  android:
  ios:
  macos:
  windows:
  linux:

homepage: https://fml.dev

repository: https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language.git

issue_tracker: https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/issues

documentation: https://github.com/AppDaddy-Software-Solutions-Inc/Flutter-Markup-Language/wiki

environment:
  sdk: '>=3.3.1 <4.0.0'
  flutter: '>=3.0.0'

screenshots:

dependencies:

  flutter:
    sdk: flutter

  # to check package status, run -> flutter pub outdated

  # Although we don't use the archive package directly, updating flutter to 3.24 requires this package to be updated
  # otherwise we get an error: Error: Method not found: 'UnmodifiableUint32ListView'. UnmodifiableUint32ListView(Uint32List(0));
  archive: ^3.6.1

  audioplayers: ^6.0.0
  # MIT

  camera: ^0.11.0
  # BSD-3-Clause

  camera_windows: ^0.2.5
  # BSD-3-Clause

  changeicon: ^1.0.0
  # MIT

  # charts_flutter: ^0.12.0
  community_charts_flutter: ^1.0.4
  # Apache-2.0

  # charts_flutter: ^0.12.0
  community_charts_common: ^1.0.4
  # Apache-2.0

  connectivity_plus: ^6.0.4
  # BSD-3-Clause

  cross_file: ^0.3.3+1
  # BSD-3-Clause

  crypto: ^3.0.2
  # BSD-3-Clause

  dart_eval: ^0.7.9
  # BSD-3-Clause

  decimal: ^3.0.2
  # Apache-2.0

  # file picker with extension support
  file_picker: ^8.1.2
  # MIT

  # Microsoft Logon - Newer versions of these packages require web < 0.5.0
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  # firebase_core_platform_interface: ^4.8.0
  # BSD-3-Clause

  fl_chart: ^0.69.0

  flutter_code_editor: ^0.3.1
  # Apache-2.0, MIT

  flex_color_picker: ^3.5.1
  # BSD-3-Clause

  flutter_beacon: ^0.5.1
  # BSD-3-Clause

  flutter_eval: ^0.7.6
  # BSD-3-Clause

  flutter_highlight: ^0.7.0
  # MIT

  flutter_image_transform: ^1.0.1
  # MIT

  flutter_map: ^7.0.2
  # BSD-3-Clause

  flutter_multi_formatter: ^2.13.0
  # MIT

  flutter_nfc_kit: ^3.4.2
  # MIT

  flutter_svg: ^2.0.10+1
  # MIT

  # Updated 2024/02/14
  flutter_typeahead: ^5.2.0
  # BSD-2-Clause

  geolocator: ^13.0.1
  # MIT

  google_fonts: ^6.2.1
  # Apache-2.0

  google_mlkit_barcode_scanning: ^0.12.0
  # MIT

  # google_mlkit_face_detection: ^0.2.0

  google_mlkit_text_recognition: ^0.13.0
  # MIT

  google_maps_flutter: ^2.9.0
  # BSD-3-Clause

  google_maps_flutter_web: ^0.5.10
  # BSD-3-Clause, MIT

  highlight: ^0.7.0
  # MIT

  hive: ^2.2.3
  # Apache-2.0

  http: ^1.2.2
  # BSD-3-Clause

  # Our library "flutter_image_transform" is blocking this update
  image: ^4.2.0
  # MIT

  intl: ^0.19.0
  # BSD-3-Clause

  jaguar_jwt: ^3.0.0
  # BSD-3-Clause

  jiffy: ^6.3.1
  # MIT

  latlong2: ^0.9.0
  # BSD-3-Clause

  mime: ^1.0.4
  # BSD-3-Clause

  mqtt_client: ^10.5.1
  # BSD-3-Clause, MIT

  ndef: ^0.3.1
  # MIT

  open_filex: ^4.2.2
  # BSD-3-Clause, MIT

  path: ^1.8.2
  # BSD-3-Clause

  path_provider: ^2.1.3
  # BSD-3-Clause

  pdf_widget_wrapper: ^1.0.4
  # Apache-2.0


  perfect_freehand: ^2.3.2
  # MIT

  # Warning, updating petitparser could potentially break the EVAL().
  petitparser: ^6.0.2
  # MIT

  pluto_grid_plus: ^8.4.0
  # MIT

  pluto_grid_plus_export: ^1.0.4
  # MIT

  pointycastle: ^3.9.1
  # MIT

  provider: ^6.0.3
  # MIT

  quiver: ^3.2.1
  # Apache-2.0

  # syncfusion_flutter_charts: ^20.1.57
  # https://pub.dev/packages/syncfusion_flutter_charts/license


  stream_channel: ^2.1.1
  # BSD-3-Clause

  web_socket_channel: ^3.0.0
  # BSD-3-Clause

  universal_html: ^2.2.4
  # Apache-2.0

  url_launcher: ^6.3.0
  # BSD-3-Clause

  uuid: ^4.4.2
  # MIT

  validators: ^3.0.0
  # MIT

  video_player: ^2.9.1
  # BSD-3-Clause

  video_player_win: ^2.3.9
  # BSD-3-Clause

  visibility_detector: ^0.4.0+2
  # BSD-3-Clause

  webview_flutter: ^4.9.0
  # BSD-3-Clause

  xml: ^6.5.0
  # MIT

  xml2json: ^6.2.3
  # MIT

  zebra123: ^1.1.5
  # MIT

  zxing_lib: ^1.1.2
  # Apache 2.0

dev_dependencies:

  # Dart linter
  lints: ^4.0.0

  # Flutter linter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/audio/
    - assets/fonts/

  fonts:
    - family: custom_icons
      fonts:
        - asset: assets/fonts/custom_icons.ttf
